const { connectDB, Company } = require('../db/mongodb');
const { STOCK_EARNINGS_TIMING } = require('../constants/earningsTiming');

const COMPANY_NAMES = {
    // Technology
    'AAPL': 'Apple Inc',
    'MSFT': 'Microsoft Corporation',
    'GOOGL': 'Alphabet Inc Class A',
    'GOOG': 'Alphabet Inc Class C',
    'META': 'Meta Platforms Inc',
    'NVDA': 'NVIDIA Corporation',
    'AVGO': 'Broadcom Inc',
    'CSCO': 'Cisco Systems Inc',
    'ADBE': 'Adobe Inc',
    'ORCL': 'Oracle Corporation',
    'NFLX': 'Netflix Inc',
    'CRM': 'Salesforce Inc',
    'AMAT': 'Applied Materials Inc',
    'ADI': 'Analog Devices Inc',
    'CDNS': 'Cadence Design Systems Inc',
    'KLAC': 'KLA Corporation',
    'SNPS': 'Synopsys Inc',
    'MCHP': 'Microchip Technology Inc',
    'MU': 'Micron Technology Inc',
    'LRCX': 'Lam Research Corporation',
    'NOW': 'ServiceNow Inc',
    'ADSK': 'Autodesk Inc',
    'FTNT': 'Fortinet Inc',
    'TEAM': 'Atlassian Corporation',
    'PANW': 'Palo Alto Networks Inc',
    'PLTR': 'Palantir Technologies Inc',

    // Financial Services
    'JPM': 'JPMorgan Chase & Co',
    'BAC': 'Bank of America Corporation',
    'WFC': 'Wells Fargo & Company',
    'GS': 'Goldman Sachs Group Inc',
    'MS': 'Morgan Stanley',
    'BLK': 'BlackRock Inc',
    'C': 'Citigroup Inc',
    'SCHW': 'Charles Schwab Corporation',
    'AXP': 'American Express Company',
    'PNC': 'PNC Financial Services Group Inc',
    'TFC': 'Truist Financial Corporation',
    'USB': 'U.S. Bancorp',
    'BK': 'Bank of New York Mellon Corp',
    'AIG': 'American International Group Inc',
    'MTB': 'M&T Bank Corporation',
    'DFS': 'Discover Financial Services',
    'COF': 'Capital One Financial Corp',
    'PRU': 'Prudential Financial Inc',
    'MMC': 'Marsh & McLennan Companies Inc',
    'AON': 'Aon plc',

    // Healthcare
    'UNH': 'UnitedHealth Group Inc',
    'JNJ': 'Johnson & Johnson',
    'LLY': 'Eli Lilly and Company',
    'PFE': 'Pfizer Inc',
    'MRK': 'Merck & Co Inc',
    'ABBV': 'AbbVie Inc',
    'TMO': 'Thermo Fisher Scientific Inc',
    'ABT': 'Abbott Laboratories',
    'DHR': 'Danaher Corporation',
    'BMY': 'Bristol-Myers Squibb Company',
    'AMGN': 'Amgen Inc',
    'CVS': 'CVS Health Corporation',
    'ELV': 'Elevance Health Inc',
    'CI': 'The Cigna Group',
    'ISRG': 'Intuitive Surgical Inc',
    'VRTX': 'Vertex Pharmaceuticals Inc',
    'REGN': 'Regeneron Pharmaceuticals Inc',
    'GILD': 'Gilead Sciences Inc',
    'HCA': 'HCA Healthcare Inc',
    'BSX': 'Boston Scientific Corporation',
    'ZTS': 'Zoetis Inc',

    // Industrial & Manufacturing
    'CAT': 'Caterpillar Inc',
    'DE': 'Deere & Company',
    'BA': 'Boeing Company',
    'HON': 'Honeywell International Inc',
    'UPS': 'United Parcel Service Inc',
    'RTX': 'RTX Corporation',
    'LMT': 'Lockheed Martin Corporation',
    'GE': 'General Electric Company',
    'MMM': '3M Company',
    'EMR': 'Emerson Electric Co',
    'ETN': 'Eaton Corporation plc',
    'ITW': 'Illinois Tool Works Inc',
    'CMI': 'Cummins Inc',
    'ROK': 'Rockwell Automation Inc',
    'GD': 'General Dynamics Corporation',
    'NSC': 'Norfolk Southern Corporation',
    'CSX': 'CSX Corporation',
    'UNP': 'Union Pacific Corporation',

    // Energy
    'XOM': 'Exxon Mobil Corporation',
    'CVX': 'Chevron Corporation',
    'COP': 'ConocoPhillips',
    'SLB': 'Schlumberger NV',
    'EOG': 'EOG Resources Inc',
    'PXD': 'Pioneer Natural Resources Company',
    'OXY': 'Occidental Petroleum Corporation',
    'PSX': 'Phillips 66',
    'VLO': 'Valero Energy Corporation',
    'MPC': 'Marathon Petroleum Corporation',
    'HAL': 'Halliburton Company',
    'BKR': 'Baker Hughes Company',

    // Consumer Staples
    'PG': 'Procter & Gamble Company',
    'KO': 'Coca-Cola Company',
    'PEP': 'PepsiCo Inc',
    'COST': 'Costco Wholesale Corporation',
    'WMT': 'Walmart Inc',
    'PM': 'Philip Morris International Inc',
    'MO': 'Altria Group Inc',
    'EL': 'The Estée Lauder Companies Inc',
    'CL': 'Colgate-Palmolive Company',
    'KMB': 'Kimberly-Clark Corporation',
    'GIS': 'General Mills Inc',
    'K': 'Kellogg Company',
    'HSY': 'The Hershey Company',
    'STZ': 'Constellation Brands Inc',

    // Communications
    'CMCSA': 'Comcast Corporation',
    'T': 'AT&T Inc',
    'VZ': 'Verizon Communications Inc',
    'DIS': 'The Walt Disney Company',
    'CHTR': 'Charter Communications Inc',
    'TMUS': 'T-Mobile US Inc'
};

// Rest of the script remains the same...
